### ISSUE TITLE
get -> post

### ISSUE THREAD

**Issue by chang-chao** [chenxiaoya1990/generate-bar-code#1]
https://github.com/chenxiaoya1990/generate-bar-code/blob/6695946e63813ac266148d09046b2b841d0fca04/demo/src/main/java/com/barcode/redis/demo/controller/BarcodeController.java#L26

**Comment by chenxiaoya1990** [comment]
The issue has been resolved.  Here's a summary of the resolution:
 @PostMapping("/generate-barcode")
    public BarcodeDTO generateBarcode(@RequestBody Map<String, String> request) {
        String userId = request.get("userId");
        return barcodeService.generateBarcode(userId);
    }
    @PostMapping("/update-barcode-status")
    public void updateBarcodeStatus(@RequestBody Map<String, String> request) {
        String barcodeCode = request.get("code");
        barcodeService.markBarcodeAsUsed(barcodeCode);
    }
