### ISSUE TITLE
return a DTO class instead of a single string

### ISSUE THREAD

**Issue by chang-chao** [chenxiaoya1990/generate-bar-code#2]
https://github.com/chenxiaoya1990/generate-bar-code/blob/6695946e63813ac266148d09046b2b841d0fca04/demo/src/main/java/com/barcode/redis/demo/controller/BarcodeController.java#L27

```
{
 "code": "0123...",
 "expireAt": time-stamp
}

```

**Comment by chenxiaoya1990** [comment]
The issue has been resolved. Here's a summary of the resolution:
![image](https://github.com/chenxiaoya1990/generate-bar-code/assets/128337000/4690e525-f694-4f91-ba96-cf797d35b8b1)
