### ISSUE TITLE
key should be code, not userId

### ISSUE THREAD

**Issue by chang-chao** [chenxiaoya1990/generate-bar-code#3]
there might be multiple barcodes for the same user at the same time( each one in each device)

https://github.com/chenxiaoya1990/generate-bar-code/blob/6695946e63813ac266148d09046b2b841d0fca04/demo/src/main/java/com/barcode/redis/demo/controller/BarcodeController.java#L37C5-L37C5

**Comment by chenxiaoya1990** [comment]
The issue has been resolved. Here's a summary of the resolution:
    @GetMapping("/get-barcode/{code}")
    public String getBarcode(@PathVariable String code) {
        return barcodeService.getBarcodeByCode(code);
    }
