### ISSUE TITLE
return code information, not the image

### ISSUE THREAD

**Issue by chang-chao** [chenxiaoya1990/generate-bar-code#4]
image can be rendered on client side.

https://github.com/chenxiaoya1990/generate-bar-code/blob/6695946e63813ac266148d09046b2b841d0fca04/demo/src/main/java/com/barcode/redis/demo/controller/BarcodeController.java#L40

**Comment by chenxiaoya1990** [comment]
The issue has been resolved. Here's a summary of the resolution:

    @GetMapping("/get-barcode/{code}")
    public String getBarcode(@PathVariable String code) {
        return barcodeService.getBarcodeByCode(code);
    }
