### ISSUE TITLE
key should be code id

### ISSUE THREAD

**Issue by chang-chao** [chenxiaoya1990/generate-bar-code#5]
https://github.com/chenxiaoya1990/generate-bar-code/blob/6695946e63813ac266148d09046b2b841d0fca04/demo/src/main/java/com/barcode/redis/demo/controller/BarcodeController.java#L49-L52

1. key should be code, not userId
2. method name of `markBarcodeAsUsed` seems better?
3.  POST or PATCH http method should be better than GET?

**Comment by chenxiaoya1990** [comment]
The issue has been resolved. Here's a summary of the resolution:

  @PostMapping("/update-barcode-status")
    public void updateBarcodeStatus(@RequestBody Map<String, String> request) {
        String barcodeCode = request.get("code");
        barcodeService.markBarcodeAsUsed(barcodeCode);
    }
