### ISSUE TITLE
key should be code, not userid

### ISSUE THREAD

**Issue by chang-chao** [chenxiaoya1990/generate-bar-code#6]
https://github.com/chenxiaoya1990/generate-bar-code/blob/6695946e63813ac266148d09046b2b841d0fca04/demo/src/main/java/com/barcode/redis/demo/controller/BarcodeController.java#L61C53-L61C59

**Comment by chenxiaoya1990** [comment]
The issue has been resolved.  Key has been changed from userID to code.
