### ISSUE TITLE
what is the merit of saving the code as base64 encoded image compared to the raw text value("0123...")?

### ISSUE THREAD

**Issue by chang-chao** [chenxiaoya1990/generate-bar-code#7]
https://github.com/chenxiaoya1990/generate-bar-code/blob/6695946e63813ac266148d09046b2b841d0fca04/demo/src/main/java/com/barcode/redis/demo/service/BarcodeService.java#L53

**Comment by chenxiaoya1990** [comment]
I misunderstood the requirement as I thought that I need to convert the string into an image to export a barcode image. The problem has been resolved.
