### ISSUE TITLE
multiple barcodes should be allowed for the same user

### ISSUE THREAD

**Issue by chang-chao** [chenxiaoya1990/generate-bar-code#8]
https://github.com/chenxiaoya1990/generate-bar-code/blob/6695946e63813ac266148d09046b2b841d0fca04/demo/src/main/java/com/barcode/redis/demo/service/BarcodeService.java#L38C23-L38C23

**Comment by chenxiaoya1990** [comment]
Key has been changed from userID to code. Please review the code. Thank you for bringing it to my attentio
