### ISSUE TITLE
Attributes associated with a code

### ISSUE THREAD

**Issue by chang-chao** [chenxiaoya1990/generate-bar-code#9]
There should be several attributes associated with a code, for example, `userId` , `expiry` (since we separate the concepts of logical and  physical expiry, it is better to have a separate field for the logical one) , `status`,  there might be more going forward, is the current data structure flexible enough for this requirement?

**Comment by chenxiaoya1990** [comment]
Hi, Mr. Chang, I have made the requested changes to the code. 
Now,  userId, physical/logical expiry, and status of the barcode has been added in the BarcodeDTO. Also, the getBarcodeByCode method has been modified to return the BarcodeDTO object. The status value for the barcode is obtained from the isBarcodeValid method.
![image](https://github.com/chenxiaoya1990/generate-bar-code/assets/128337000/46e48514-4ee9-41cd-97e8-205bcc0a17e8)

Here is the updated code of generateBarcode and getBarcodeByCode  :

public BarcodeDTO generateBarcode(String userId) {
		
	    // Generate the barcode by combining the user's hash code with a random long value,
	    // and make it 24 characters long.
		String barcode = StringUtils.rightPad(
				String.valueOf(userId.hashCode() & Integer.MAX_VALUE)
						+ String.valueOf(randomCode.nextLong() & Long.MAX_VALUE),
				24, "0").substring(0, 24);

		String key = BARCODE_PREFIX + barcode;

		// Calculate the total expiration time for physical expiration, including the buffer.
		long physicalExpirationTime = EXPIRATION_SECONDS + BUFFER_SECONDS;

		// Calculate the total logical expiration time, without the buffer.
		long logicalExpirationTime = EXPIRATION_SECONDS;

		// Link the barcode to the userID and set the expiration time for the barcode.
		redisTemplate.opsForValue().set(key, barcode, physicalExpirationTime, TimeUnit.SECONDS);

		// Calculate the expiration timestamps (current time + totalExpirationTime)
		long physicalExpiryMillis = System.currentTimeMillis() + (physicalExpirationTime * 1000);
		long logicalExpiryMillis = System.currentTimeMillis() + (logicalExpirationTime * 1000);

		// Create the BarcodeDTO instance with the barcode value and expiration timestamps
		BarcodeDTO barcodeDTO = new BarcodeDTO();
		barcodeDTO.setUserId(userId);
		barcodeDTO.setCode(barcode);
		barcodeDTO.setPhysicalExpireAt(new Timestamp(physicalExpiryMillis));
		barcodeDTO.setLogicalExpireAt(new Timestamp(logicalExpiryMillis));
		barcodeDTO.setStatus(true);

		// Convert BarcodeDTO to JSON string
		ObjectMapper objectMapper = new ObjectMapper();
		String barcodeDTOJson;
		try {
			barcodeDTOJson = objectMapper.writeValueAsString(barcodeDTO);
		} catch (JsonProcessingException e) {
			e.printStackTrace();
			return null;
		}


	public BarcodeDTO getBarcodeByCode(String code) {
		String key = BARCODE_PREFIX + code;
		String barcodeValue = redisTemplate.opsForValue().get(key);

		if (barcodeValue != null) {
			// Get the entire BarcodeDTO JSON string from Redis
			String dtoKey = key + ":dto";
			String barcodeDTOJson = redisTemplate.opsForValue().get(dtoKey);

			// Convert JSON string back to BarcodeDTO object
			ObjectMapper objectMapper = new ObjectMapper();
			BarcodeDTO barcodeDTO;
			try {
				barcodeDTO = objectMapper.readValue(barcodeDTOJson, BarcodeDTO.class);
			} catch (JsonProcessingException e) {
				e.printStackTrace();
				return null;
			}

			// Set the current status from isBarcodeValid
			boolean currentStatus = isBarcodeValid(code);
			barcodeDTO.setStatus(currentStatus);
			// Set PhysicalExpireAt to null (as it is not necessary to be shown when get)
			barcodeDTO.setPhysicalExpireAt(null);
			return barcodeDTO;
		}

		return null; // Return null if the barcode is not found in Redis.
	}
